[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tidal-wave"
dynamic = ["version"]
description = "A tool to wave at the TIDAL music service."
authors = [{ name = "colinho", email = "pypi@colin.technology" }]
maintainers = [{ name = "colinho", email = "pypi@colin.technology" }]
license = { file = "LICENSE" }
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10,<3.15"
classifiers = [
    "Intended Audience :: End Users/Desktop",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Video",
]
dependencies = [
    "backoff==2.2.1",
    "cachecontrol==0.14.3",
    "dataclass-wizard==0.39.1",
    "ffmpeg-python==0.2.0",
    "mutagen==1.47.0",
    "m3u8==6.0.0",
    "platformdirs==4.5.1",
    "pycryptodome==3.23.0",
    "requests[socks]>=2.32.4",
    "typer==0.26.1",
]

[project.scripts]
tidal-wave = "tidal_wave.main:app"

[project.urls]
Homepage = "https://github.com/ebb-earl-co/tidal-wave"

[dependency-groups] # https://docs.astral.sh/uv/reference/settings/#dev-dependencies
build = [
    "pyinstaller==6.21.0",
    "uv>=0.9.0"
]
dev = [
    "ruff"
]

[tool.hatch.build]
reproducible = true

[tool.hatch.build.targets.sdist]
include = [
  "tidal_wave/",
]
exclude = [
  "pyinstaller.py"
]

[tool.hatch.version]
path = "tidal_wave/main.py"

[tool.ruff]  # https://docs.astral.sh/ruff/configuration/
indent-width = 4
line-length = 88
target-version = "py38"

[tool.ruff.format]
indent-style = "space"
quote-style = "double"

[tool.uv]
compile-bytecode = true  # https://docs.astral.sh/uv/reference/settings/#compile-bytecode
package = true  # https://docs.astral.sh/uv/reference/settings/#package
required-version = ">=0.9.0"  # https://docs.astral.sh/uv/reference/settings/#required-version
