name: Pyapp Build on macOS for macOS x86_64
on:
  release:
    types: ["published"]

env:
  PYAPP_DISTRIBUTION_EMBED: 1
  PYAPP_METADATA_TEMPLATE: "{project}, version {version}"
  PYAPP_PROJECT_FEATURES: "all"
  PYAPP_PROJECT_NAME: "tidal-wave"
  PYAPP_PROJECT_VERSION: ${{ github.event.release.tag_name }}
  PYAPP_PYTHON_VERSION: "3.11"
  # https://doc.rust-lang.org/cargo/reference/config.html#buildtarget
  CARGO_BUILD_TARGET: "x86_64-apple-darwin"

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pyapp from crates.io (also builds executable)
        uses: baptiste0928/cargo-install@v3
        with:
          crate: pyapp
          version: 0.16.0
          args: "--root ~/.cargo"

      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: tidal-wave_${{ github.event.release.tag_name }}_py311_macos.pyapp
          path: ~/.cargo/bin/pyapp
          compression-level: 0
          if-no-files-found: error
          retention-days: 1

      - name: Rename just-compiled binary
        run: |
          mv /Users/runner/.cargo-install/pyapp/bin/pyapp ${{ github.workspace }}/tidal-wave_py311_macos.pyapp

      - name: Test just-compiled binary
        run: ${{ github.workspace }}/tidal-wave_py311_macos.pyapp --help

      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: tidal-wave_${{ github.event.release.tag_name }}_py311_macos.pyapp
          path: ${{ github.workspace }}/tidal-wave_py311_macos.pyapp
          compression-level: 0
          if-no-files-found: error
          retention-days: 1

      - name: Add artifact to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          fail_on_unmatched_files: true
          files: ${{ github.workspace }}/tidal-wave_py311_macos.pyapp
