name: Pyapp Build on macOS for macOS arm64
on:
  release:
    types: ["published"]
  push:
    branches: ["trunk"]

env:
  PYAPP_PROJECT_NAME: "tidal-wave"
  # PYAPP_PROJECT_VERSION: ${{ github.event.release.tag_name }}
  PYAPP_PROJECT_VERSION: "2024.1.14"
  PYAPP_DISTRIBUTION_EMBED: 1
  PYAPP_PYTHON_VERSION: 3.11

permissions:
  contents: write

jobs:
  build:
    runs-on: flyci-macos-large-latest-m1

    steps:
    - uses: actions/checkout@v4

    - name: Install pyapp from crates.io (also builds executable)
      uses: baptiste0928/cargo-install@v2
      with:
        crate: pyapp
        version: 0.14.0

    - name: Rename just-compiled binary
      run: |
        mv /Users/runner/.cargo-install/pyapp/bin/pyapp ${{ github.workspace }}/tidal-wave_py311_macos_arm64.pyapp

    - name: Test just-compiled binary
      run: ${{ github.workspace }}/tidal-wave_py311_macos_arm64.pyapp --help

    - name: Add (upload) artifact to release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ github.token }}
        fail_on_unmatched_files: true
        files: ${{ github.workspace }}/tidal-wave_py311_macos_arm64.pyapp
