name: Pyapp Build on Ubuntu for GNU/Linux x86_64
on:
  release:
    types: ["published"]

env:
  PYAPP_PROJECT_NAME: "tidal-wave"
  PYAPP_PROJECT_VERSION: ${{ github.event.release.tag_name }}
  PYAPP_DISTRIBUTION_EMBED: 1
  PYAPP_PYTHON_VERSION: 3.11

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pyapp from crates.io (also builds executable)
      uses: baptiste0928/cargo-install@v2
      with:
        crate: pyapp
        version: 0.14.0

    - name: Rename just-compiled binary
      shell: bash
      run: |
        mv /home/runner/.cargo-install/pyapp/bin/pyapp ${{ github.workspace }}/tidal-wave_py311.pyapp

    - name: Test just-compiled binary
      run: |
        chmod +x ${{ github.workspace }}/tidal-wave_py311.pyapp
        ${{ github.workspace }}/tidal-wave_py311.pyapp --help

    - name: Add (upload) artifact to release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ github.token }}
        fail_on_unmatched_files: true
        files: ${{ github.workspace }}/tidal-wave_py311.pyapp

