name: Pyapp Build on macOS
on:
  release:
    types: ["published"]

env:
  PYAPP_PROJECT_NAME: "tidal-wave"
  PYAPP_PROJECT_VERSION: ${{ github.event.release.tag_name }}
  PYAPP_EMBED: 1
  PYAPP_PYTHON_VERSION: 3.11

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pyapp from crates.io (also builds executable)
      uses: baptiste0928/cargo-install@v2
      with:
        crate: pyapp
        version: 0.13.0

    - name: Rename just-compiled binary
      run: |
        mv /Users/runner/.cargo-install/pyapp/bin/pyapp /Users/runner/.cargo-install/pyapp/bin/tidal-wave_${{ github.event.release.tag_name }}_macos.pyapp

    - name: Test just-compiled binary
      run: |
        /home/runner/.cargo-install/tidal-wave_${{ github.event.release.tag_name }}_macos.pyapp --help

    - name: Add (upload) artifact to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: /Users/runner/.cargo-install/pyapp/bin/tidal-wave_${{ github.event.release.tag_name }}_macos.pyapp
