name: Pyapp Build on Ubuntu for GNU/Linux x86_64
on:
  release:
    types: ["published"]

env:
  PYAPP_DISTRIBUTION_EMBED: 1
  PYAPP_METADATA_TEMPLATE: "{project}, version {version}"
  PYAPP_PROJECT_FEATURES: "all"
  PYAPP_PROJECT_NAME: "tidal-wave"
  PYAPP_PROJECT_VERSION: ${{ github.event.release.tag_name }}
  PYAPP_PYTHON_VERSION: "3.11"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pyapp from crates.io (also builds executable)
        uses: baptiste0928/cargo-install@v3
        with:
          crate: pyapp
          version: 0.16.0

      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: tidal-wave_${{ github.event.release.tag_name }}_py311.pyapp
          path: /home/runner/.cargo-install/pyapp/bin/pyapp
          compression-level: 0
          if-no-files-found: error
          retention-days: 1

      - name: Test just-compiled binary
        run: |
          chmod +x /home/runner/.cargo-install/pyapp/bin/pyapp
          /home/runner/.cargo-install/pyapp/bin/pyapp --help

      - name: Rename just-compiled binary
        shell: bash
        run: |
          mv /home/runner/.cargo-install/pyapp/bin/pyapp ${{ github.workspace }}/tidal-wave_py311.pyapp

      - name: Add artifact to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          fail_on_unmatched_files: true
          files: ${{ github.workspace }}/tidal-wave_py311.pyapp
