name: Pyapp Build on Windows for 64-bit Windows
on:
  release:
    types: ["published"]

env:
  PYAPP_DISTRIBUTION_EMBED: 1
  PYAPP_METADATA_TEMPLATE: "{project}, version {version}"
  PYAPP_PROJECT_FEATURES: "all"
  PYAPP_PROJECT_NAME: "tidal-wave"
  PYAPP_PROJECT_VERSION: ${{ github.event.release.tag_name }}
  PYAPP_PYTHON_VERSION: "3.11"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pyapp from crates.io (also builds executable)
        uses: baptiste0928/cargo-install@v3
        with:
          crate: pyapp
          version: 0.16.0

      - name: Test just-compiled binary
        shell: pwsh
        run: |
          & "C:\Users\runneradmin\.cargo-install\pyapp\bin\pyapp.exe" --help

      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: tidal-wave_${{ github.event.release.tag_name }}_py311_pyapp.exe
          path: C:\Users\runneradmin\.cargo-install\pyapp\bin\pyapp.exe
          compression-level: 0
          if-no-files-found: error
          retention-days: 1

      - name: Rename just-compiled EXE
        shell: pwsh
        run: |
          Move-Item "C:\Users\runneradmin\.cargo-install\pyapp\bin\pyapp.exe" ${{ github.workspace }}\tidal-wave_py311_pyapp.exe

      - name: Add artifact to release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          fail_on_unmatched_files: true
          files: ${{ github.workspace }}\tidal-wave_py311_pyapp.exe
