name: Pyapp Build on macOS for macOS arm64
on:
  release:
    types: ["published"]

env:
  PYAPP_PROJECT_NAME: "tidal-wave"
  PYAPP_PROJECT_VERSION: ${{ github.event.release.tag_name }}
  PYAPP_DISTRIBUTION_EMBED: 1
  PYAPP_PYTHON_VERSION: 3.11
  # https://doc.rust-lang.org/cargo/reference/config.html#buildtarget
  CARGO_BUILD_TARGET: "aarch64-apple-darwin"

permissions:
  contents: write

jobs:
  build:
    runs-on: flyci-macos-large-latest-m1

    steps:
      - uses: actions/checkout@v4

      - name: Install pyapp from crates.io (also builds executable)
        uses: baptiste0928/cargo-install@v3
        with:
          crate: pyapp
          version: 0.15.1

      - name: Rename just-compiled binary
        run: |
          mv /Users/runner/.cargo-install/pyapp/bin/pyapp ${{ github.workspace }}/tidal-wave_py311_macos_arm64.pyapp

      - name: Test just-compiled binary
        run: ${{ github.workspace }}/tidal-wave_py311_macos_arm64.pyapp --help

      - name: Upload artifact
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: tidal-wave_${{ github.event.release.tag_name }}_py311_macos_arm64.pyapp
          path: ${{ github.workspace }}/tidal-wave_py311_macos_arm64.pyapp
          compression-level: 0
          if-no-files-found: error
          retention-days: 1

      - name: Add (upload) artifact to release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          fail_on_unmatched_files: true
          files: ${{ github.workspace }}/tidal-wave_py311_macos_arm64.pyapp
