name: Pyapp Build on Ubuntu for GNU/Linux x86_64
on:
  release:
    types: ["published"]
  push:
    branches: ["develop", "trunk"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build FFmpeg from source
      run: |
        mkdir ~/ffmpeg_sources ~/ffmpeg_build ~/bin
        cd ~/ffpmeg_sources
        curl --output ffmpeg-6.1.1.tar.gz https://ffmpeg.org/releases/ffmpeg-6.1.1.tar.gz
        tar xzf ffmpeg-6.1.1.tar.gz
        cd ffmpeg-6.1.1
        PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
          --prefix="$HOME/ffmpeg_build" \
          --pkg-config-flags="--static" \
          --extra-cflags="-I$HOME/ffmpeg_build/include" \
          --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
          --extra-libs="-lpthread -lm" \
          --ld="g++" \
          --bindir="$HOME/bin"
        PATH="$HOME/bin:$PATH" make -j$(nproc)
        make install
        hash -r
        mv "$HOME/bin/ffmpeg" /opt/ffmpeg

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"  # caching pip dependencies

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install pyinstaller

    - name: Create Executable with Pyinstaller
      run: |
        pyinstaller \
          --distpath ./.dist \
          --workpath ./.build \
          --onefile \
          --name tidal-wave_linux \
          --paths tidal_wave \
          --add-data "README.md:." \
          --add-data "/opt/ffmpeg:." \
          ./pyinstall.py 
    
    - name: Test just-compiled binary
      run: |
        tidal-wave_linux --help

    - name: Add (upload) artifact to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: tidal-wave_linux
