name: Build Python package
on:
  release:
    types: ["published"]

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/tidal-wave

    permissions:

      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"  # caching pip dependencies

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install build
    
    - name: Build package
      run: python3 -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Add (upload) artifact to release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        files: |
          dist/tidal-wave-${{ github.event.release.tag_name }}.tar.gz
          dist/tidal_wave-${{ github.event.release.tag_name }}-py3-none-any.whl

