---
name: Build Python package
on:
  release:
    types: ["published"]

jobs:
  build:
    runs-on: ubuntu-24.04

    environment:
      name: pypi
      url: https://pypi.org/p/tidal-wave

    permissions:
      contents: write
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: 3.14.0

      - name: Install dependencies
        env:
          UV_NO_MANAGED_PYTHON: 1
        run: |
          uv sync --locked --no-group build --no-group dev

      - name: Build package
        env:
          UV_NO_MANAGED_PYTHON: 1
        run: uv build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Add artifacts to release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b  # v2.5.0
        with:
          token: ${{ github.token }}
          files: |
            dist/tidal-wave-${{ github.event.release.tag_name }}.tar.gz
            dist/tidal_wave-${{ github.event.release.tag_name }}-py3-none-any.whl
