---
name: Python linting with Ruff
on:
  push:
    branches: ["trunk", "develop"]
  pull_request:
    branches: ["trunk", "develop"]
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.13t"]
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
        os: [ubuntu-22.04, ubuntu-24.04, windows-2022, windows-2025, macos-14, macos-15, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0
      - name: Install uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d  # v7.1.0
        with:
          python-version: ${{ matrix.version }}
          version: ">=0.9"
      - name: Format with Ruff
        run: uv run --no-project --with ruff ruff format --diff ./tidal_wave/
      - name: Lint with Ruff
        run: uv run --no-project --with ruff ruff check --statistics --exclude pyinstaller.py ./tidal_wave/
